;             
CREATE USER IF NOT EXISTS "SA1" PASSWORD '' ADMIN;            
DROP TABLE IF EXISTS "PUBLIC"."TEST" CASCADE; 
CREATE SEQUENCE "PUBLIC"."BUG_ENTITY_SEQ" START WITH 4 BELONGS_TO_TABLE;      
CREATE SEQUENCE "PUBLIC"."BUG_CONFIG_ENTITY_SEQ" START WITH 1 BELONGS_TO_TABLE;               
CREATE CACHED TABLE "PUBLIC"."TEST"(
    "ID" INT NOT NULL,
    "NAME" VARCHAR(255)
);     
ALTER TABLE "PUBLIC"."TEST" ADD CONSTRAINT "PUBLIC"."CONSTRAINT_2" PRIMARY KEY("ID");         
-- 1 +/- SELECT COUNT(*) FROM PUBLIC.TEST;    
INSERT INTO "PUBLIC"."TEST" VALUES
(1, 'Hi');
